### PR TITLE
3r assignment code review

### PR DESCRIPTION
**Pull request by aryanabuelna**

### CODE REVIEW

**Comment by aryanabuelna** [comment]
comment

**Comment by aryanabuelna** [comment]
I think you did a good job by creating addAssignment.js I think you are heading in the correct direction. Just make sure that the user is able to add name, due date and the course for the assignment. I see you attempted to add the route but have it commented out. I suggest attending O.H to get support form the TA if this is something that is stumping you.

**Comment by bruiz0412** [comment]
Hey Aryana! I saw that you added NewStudent.js, I think this was a step in the correct direction.

**Comment by bruiz0412** [comment]
Oh Noooo, it is not rendernig properly in react when run in the terminal but I think you can get help from the TA and you would be good. Nice Job!

**Pull request merged**
